// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4yxXEX4dnK7aqWnZJrgLWinejv3eOFFE',
    appId: '1:400863639679:web:4c0ddd0dd74bf696aca74a',
    messagingSenderId: '400863639679',
    projectId: 'krenter-3989e',
    authDomain: 'krenter-3989e.firebaseapp.com',
    storageBucket: 'krenter-3989e.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN-z1ul1ksxqjK-UZVNdNk4hjeV519zIk',
    appId: '1:400863639679:android:b1bc20e10b766f63aca74a',
    messagingSenderId: '400863639679',
    projectId: 'krenter-3989e',
    storageBucket: 'krenter-3989e.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_UOopOdnPwTtmOecUcVj9uauzHG8RaMw',
    appId: '1:400863639679:ios:16cfb51e0fc5986aaca74a',
    messagingSenderId: '400863639679',
    projectId: 'krenter-3989e',
    storageBucket: 'krenter-3989e.firebaseapp.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_UOopOdnPwTtmOecUcVj9uauzHG8RaMw',
    appId: '1:400863639679:ios:16cfb51e0fc5986aaca74a',
    messagingSenderId: '400863639679',
    projectId: 'krenter-3989e',
    storageBucket: 'krenter-3989e.firebaseapp.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4yxXEX4dnK7aqWnZJrgLWinejv3eOFFE',
    appId: '1:400863639679:web:c8167ee6c88690b2aca74a',
    messagingSenderId: '400863639679',
    projectId: 'krenter-3989e',
    authDomain: 'krenter-3989e.firebaseapp.com',
    storageBucket: 'krenter-3989e.firebaseapp.com',
  );

}